// <auto-generated />
namespace PostCard.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class confirmPass : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(confirmPass));
        
        string IMigrationMetadata.Id
        {
            get { return "202001101410461_confirmPass"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
